version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: learn_with_me_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - RAILS_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_DB_DEVELOPMENT=learn_with_me_development
      - POSTGRES_DB_TEST=learn_with_me_test
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
      - node_modules:/rails/node_modules
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    stdin_open: true
    tty: true
    command: >
      bash -c "
        bin/rails db:prepare &&
        bin/rails server -b 0.0.0.0
      "

  # Service for running tests
  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - RAILS_ENV=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_DB_TEST=learn_with_me_test
      - REDIS_URL=redis://redis:6379/1
      - CI=true
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    profiles:
      - test
    command: >
      bash -c "
        bin/rails db:test:prepare &&
        bin/rails test &&
        bin/rails test:system
      "

volumes:
  postgres_data:
  redis_data:
  bundle_cache:
  node_modules:

